export enum Propagation {
    REQUIRED = 'REQUIRED',
    REQUIRES_NEW = 'REQUIRES_NEW',
    MANDATORY = 'MANDATORY',
    // SUPPORTS = 'SUPPORTS',
    // NOT_SUPPORTED = 'NOT_SUPPORTED',
    // NEVER = 'NEVER'
}